Chapter 3 — Datatypes in Python
Write a Python program to display the addition of two complex numbers.
Write a Python program to convert numbers from different number systems into the decimal number system.
Write a Python program using a function to convert numbers from different number systems into the decimal number system.
Write a Python program to create a bytes type array and display its elements.
Write a Python program to create a bytearray type array and retrieve its elements.
Chapter 5 — Input and Output
Write a Python program to accept a string from the keyboard and display it.
Write a Python program to accept a character as a string.
Write a Python program to accept a single character from the keyboard.
Write a Python program to accept an integer number from the keyboard.
Write a Python program to accept an integer number from the keyboard using another method.
Write a Python program to accept a floating-point number from the keyboard.
Write a Python program to accept two integer numbers from the keyboard.
Write a Python program to accept two numbers and find their sum.
Write a Python program to find the sum and product of two numbers.
Write a Python program to convert numbers from other number systems into the decimal number system.
Write a Python program to accept three integers in the same line and display their sum.
Write a Python program to accept three integers separated by commas and display their sum.
Write a Python program to accept a group of strings separated by commas and display them.
Write a Python program to evaluate an expression entered from the keyboard.
Write a Python program to accept a list and display it.
Write a Python program to accept a tuple and display it.
Write a Python program to display command-line arguments.
Write a Python program to find the sum of two numbers using command-line arguments.
Write a Python program to find the sum of even numbers using command-line arguments.
Write a Python program using argparse to find the square of a given number.
Write a Python program to add two numbers using argparse.
Write a Python program to find the power of a number when raised to a particular power.
Write a Python program to accept one or more arguments and display them as list elements.
Chapter 6 — Control Statements
Conditional Statements
Write a Python program to calculate the area of a circle.
Write a Python program to express a digit in words.
Write a Python program to display a group of messages when a condition is true.
Write a Python program to test whether a number is even or odd.
Write a Python program to accept a number from the keyboard and test whether it is even or odd.
Write a Python program to test whether a given number is between 1 and 10.
Write a Python program to determine whether a given number is zero, positive, or negative.
Write a Python program to accept a numeric digit from the keyboard and display it in words.
Loops
Write a Python program to display numbers from 1 to 10 using a while loop.
Write a Python program to display even numbers between 100 and 200.
Write a Python program to display even numbers between m and n.
Write a Python program to display characters of a string using a for loop.
Write a Python program to display each character of a string using sequence indexing.
Write a Python program to display odd numbers from 1 to 10 using the range() function.
Write a Python program to display numbers from 10 to 1 in descending order.
Write a Python program to display the elements of a list using a for loop.
Write a Python program to display and find the sum of a list of numbers using a for loop.
Write a Python program to display and find the sum of a list of numbers using a while loop.
Write a Python program to display stars in a right-angled triangular form using nested loops.
Write a Python program to display stars in a right-angled triangular form using a single loop.
Write a Python program to display stars in an equilateral triangular form using a single for loop.
Write a Python program to display numbers from 1 to 100 in proper format.
Write a Python program to search for an element in a list.
break, continue, pass, assert
Write a Python program to display numbers from 10 to 6 and break the loop when the number is 5.
Write a Python program to display numbers from 1 to 5 using the continue statement.
Write a Python program to demonstrate that the pass statement does nothing.
Write a Python program to retrieve only negative numbers from a list.
Write a Python program using assert to ensure that the user enters a number greater than zero.
Write a Python program to handle the AssertionError generated by an assert statement.
Functions and Series
Write a function to find the sum of two numbers.
Write a Python program containing a function that returns the sum of two numbers.
Write a Python program to display a series of prime numbers.
Write a Python program to generate the Fibonacci number series.
Write a Python program to calculate the sine value of an angle in degrees using the sine series.
Write a Python program to calculate the cosine value of an angle in degrees using the cosine series.
Write a Python program to evaluate the exponential series.
Chapter 7 — Arrays in Python
Python Array Module
Write a Python program to create an integer-type array.
Write a Python program to create another integer-type array.
Write a Python program to create an array containing a group of characters.
Write a Python program to create one array from another array.
Write a Python program to retrieve elements of an array using array indexing.
Write a Python program to retrieve elements of an array using a while loop.
Write a Python program to demonstrate the effects of slicing operations on an array.
Write a Python program to retrieve and display a range of elements from an array using slicing.
Write a Python program to demonstrate various methods of the array class.
Write a Python program to store student marks in an array and find the total and percentage.
Write a Python program to sort array elements using the bubble sort technique.
Write a Python program to search for the position of an element using sequential search.
Write a Python program to search for the position of an element using the index() method.
NumPy Arrays
Write a Python program to create a simple array using NumPy.
Write another version of the NumPy array creation program.
Write another version of the NumPy array creation program.
Write a Python program to create a character-type array containing a group of characters.
Write a Python program to create a string-type array using NumPy.
Write a Python program to create an array from another array.
Write a Python program to create an array with five equally spaced points using linspace().
Write a Python program to create an array using logspace().
Write a Python program to create an array containing even numbers up to 10.
Write a Python program to create arrays using zeros() and ones().
Write a Python program to perform mathematical operations on a NumPy array.
Write a Python program to compare two arrays and display the resulting Boolean array.
Write a Python program to demonstrate the effects of the any() and all() functions.
Write a Python program to understand the use of the topical() function. (OCR unclear; likely a NumPy function such as where().)
Write a Python program to compare corresponding elements of two arrays and retrieve the biggest elements.
Write a Python program to retrieve non-zero elements from an array.
Write a Python program to alias an array and understand the effect of aliasing.
Write a Python program to create a view of an existing array.
Write a Python program to copy an array into another array.
Write a Python program to understand slicing operations on NumPy arrays.
Write a Python program to retrieve and display NumPy array elements using indexing.
Write a Python program to retrieve elements from a 2D array using for loops.
Write a Python program to retrieve elements from a 3D array.
Write a Python program to accept a matrix from the keyboard and display its transpose.
Write a Python program to accept two matrices and find their product.
Chapter 8 — Strings and Characters
Write a Python program to access each element of a string in forward and reverse order using a while loop.
Write a Python program to access characters of a string using a for loop.
Write a Python program to check whether a substring exists in a main string.
Write a Python program to find the first occurrence of a substring in a given string.
Write a Python program to find the first occurrence of a substring using the index() method.
Write a Python program to display all positions of a substring in a given string.
Write another version of the program to display all positions of a substring.
Write a Python program to accept and display a group of numbers.
Write a Python program to determine the type of character entered by the user.
Write a Python program to sort a group of strings alphabetically.
Write a Python program to search for the position of a string in a group of strings.
Write a Python program to find the length of a string without using the len() function.
Write a Python program to find the number of words in a string.
Write a Python program to insert a substring into a string at a particular position.
Chapter 9 — Functions
Write a function that accepts two values and finds their sum.
Write a Python program to find the sum of two numbers and return the result from a function.
Write a function to test whether a number is even or odd.
Write a Python program to calculate the factorial of a number.
Write a Python function to check whether a given number is prime.
Write a Python program to generate prime numbers using a function that tests whether a number is prime.
Write a Python program to demonstrate how a function can return two values.
Write a function that returns the results of addition, subtraction, multiplication, and division.
Write a Python program to assign a function to a variable.
Write a Python program to define a function inside another function.
Write a Python program to pass a function as a parameter to another function.
Write a Python program to demonstrate how a function can return another function.
Write a Python program to pass an integer to a function and modify it.
Write a Python program to pass a list to a function and modify it.
Write a Python program to demonstrate that creating a new object inside a function does not modify the outside object.
Write a Python program to demonstrate positional arguments.
Write a Python program to demonstrate keyword arguments.
Write a Python program to demonstrate default arguments.
Write a Python program to demonstrate variable-length arguments.
Write a Python program to demonstrate keyword variable-length arguments.
Write a Python program to understand global and local variables.
Write a Python program to access and modify a global variable inside a function.
Write a Python program to get a copy of a global variable inside a function and work with it.
Write a function to accept a group of numbers and find their total and average.
Write a function to display a group of strings.
Recursion
Write a Python program to calculate factorial using recursion.
Write a Python program to solve the Tower of Hanoi problem.
Lambda Functions
Write a Python program to create a lambda function that returns the square of a number.
Write a lambda function to calculate the sum of two numbers.
Write a lambda function to find the bigger of two numbers.
Write a Python program using filter() to filter even numbers from a list.
Write a lambda function that returns even numbers from a list.
Write a Python program to find squares of elements in a list.
Write a lambda function to return squares of elements in a list.
Write a Python program to find the products of elements of two different lists using lambda.
Write a lambda function to calculate products of elements of a list.
Decorators
Write a decorator to increase the value returned by a function by 2.
Write a Python program to apply a decorator to a function using the @ symbol.
Write a Python program to create two decorators.
Write a Python program to apply two decorators to the same function using @.
Generators
Write a Python program to create a generator that returns a sequence of numbers from x to y.
Write a generator that returns characters from A to C.
Modules and Packages
Write a Python program to calculate the gross salary and net salary of an employee.
Write a Python program to create a module containing functions.
Write a Python program to import and use the arith.py module.
Write a Python program showing how to use a module belonging to a package.
Write a Python program using the __name__ variable.
Write a Python program that imports the previous Python program as a module.
Chapter 10 — Lists and Tuples
Write a Python program to create lists containing different types of elements.
Write a Python program to create lists using the range() function.
Write a Python program to access list elements using loops.
Write a Python program to display list elements in reverse order.
Write a Python program to demonstrate list-processing methods.
Write a Python program to find the maximum and minimum elements in a list.
Write a Python program to sort list elements using bubble sort.
Write a Python program to find how many times an element occurs in a list.
Write a Python program to find common elements in two lists.
Write a Python program to create a list containing employee data and retrieve details of a particular employee.
Write a Python program to create a nested list and display its elements.
Write a Python program to retrieve and display elements from a matrix.
Write a Python program to add two matrices using lists.
Write a Python program to accept tuple elements and find their sum and average.
Write a Python program to find the first occurrence of an element in a tuple.
Write a Python program to sort a tuple containing nested tuples.
Write a Python program to insert a new element into a tuple at a specified position.
Write a Python program to modify or replace an element of a tuple.
Write a Python program to delete an element from a particular position in a tuple.
Chapter 11 — Dictionaries
Write a Python program to create a dictionary containing employee details and retrieve values using keys.
Write a Python program to retrieve keys, values, and key-value pairs from a dictionary.
Write a Python program to create a dictionary and find the sum of its values.
Write a Python program to create a dictionary from keyboard input and display its elements.
Write a Python program to create a dictionary containing cricket players and their scores and retrieve a player's score by entering their name.
Write a Python program to use a for loop to retrieve elements of a dictionary.
Write a Python program to find the frequency of each letter in a string using a dictionary.
Write a Python program to sort dictionary elements based on a key or value.
Write a Python program to convert two lists into key-value pairs of a dictionary.
Write a Python program to convert a string into key-value pairs and store them in a dictionary.
Write a Python function to accept a dictionary and display its elements.
Write a Python program to create an ordered dictionary whose element order is preserved.
Chapter 13 — Classes and Objects
Write a Python program to define a Student class, create an object, call its method, and display student details.
Write a Python program to create a Student class with a constructor having more than one parameter.
Write a Python program to demonstrate instance variables.
Write a Python program to demonstrate class/static variables.
Write a Python program using a Student class with instance methods to process data of several students.
Write a Python program to store data in instances using mutator methods and retrieve data using accessor methods.
Write a Python program to use a class method to handle common features of all instances of a Bird class.
Write a Python program to create a static method that counts the number of instances created for a class.
Write a Python program to create a static method that calculates the square root of a number.
Write a Python program to create a Bank class for handling deposits and withdrawals using instance methods.
Write a Python program to create an Emp class and make its members available to another class, Myclass.
Write a Python program to calculate the power of a number using a static method.
Write a Python program to create nested classes within a Person class.
Write another version of the program using a nested DOB class inside Person.
Chapter 14 — Inheritance and Polymorphism
Write a Python program to create a Teacher class and store it in teacher.py.
Write a Python program to use the Teacher class.
Write a Python program to create a Student class and store it in student.py.
Write a Python program to use the Student class available in student.py.
Write a Python program to create a Student class by deriving it from the Teacher class.
Write a Python program to access the base-class constructor from a subclass.
Write a Python program to override the superclass constructor and method in a subclass.
Write a Python program to call the superclass constructor using super().
Write a Python program to access the base-class constructor and method using super().
Write a Python program demonstrating single inheritance.
Write a Python program implementing multiple inheritance using two base classes.
Write a Python program to demonstrate constructor behavior in multiple inheritance.
Write a Python program to access instance variables of both base classes in multiple inheritance.
Write a Python program to demonstrate method execution order using MRO.
Write a Python program to invoke a method on an object without knowing its class/type.
Write a Python program to call a method that may not appear in the object.
Write a Python program to check the object type and determine whether a method exists.
Write a Python program to use the addition operator on different types of objects.
Write a Python program to use the addition operator to add the contents of two objects.
Write a Python program to overload the + operator for class objects.
Write a Python program to overload the > operator.
Write a Python program to overload the * operator.
Write a Python program to demonstrate method overloading for two or three numbers.
Write a Python program to override a superclass method in a subclass.
Chapter 15 — Abstract Classes and Interfaces
Write a Python program to demonstrate that a class method is shared by all instances.
Write a Python program to create an abstract class and subclasses that implement its abstract method.
Write a Python program to create a Car abstract class containing an instance variable, a concrete method, and two abstract methods.
Write a Python program in which the Maruti subclass implements the abstract methods of Car.
Write a Python program in which the Santro subclass implements the abstract methods of Car.
Write a Python program to develop an interface that connects to any database.
Write a Python program containing a Printer interface and subclasses that send text to different printers.
Chapter 16 — Exceptions
Write a Python program to understand compile-time errors.
Write a Python program to demonstrate a compile-time error.
Write a Python program to understand runtime errors.
Write a Python program to demonstrate a runtime error.
Write a Python program to increment an employee's salary by 15%.
Write a Python program to understand the effect of an exception.
Write a Python program to handle ZeroDivisionError.
Write a Python program to handle the syntax error generated by the eval() function.
Write a Python program to handle IOError produced by open().
Write a Python program to handle multiple exceptions.
Write a Python program to demonstrate try with finally.
Write a Python program using assert and catching AssertionError.
Write a Python program to create a user-defined exception and raise it when required.
Write a Python program to use an assert statement with a message.
Write a Python program that creates a log file containing error and critical messages.
Write a Python program to store exception messages in a log file.
Chapter 17 — Files in Python
Write a Python program to create a text file and store individual characters.
Write a Python program to read characters from a text file.
Write a Python program to store a group of strings in a text file.
Write a Python program to read all strings from a text file and display them.
Write a Python program to append data to an existing file and display the complete file.
Write a Python program to check whether a file exists.
Write a Python program to count the number of lines, words, and characters in a text file.
Write a Python program to copy an image file into another file.
Write a Python program to use with to open a file and write strings into it.
Write a Python program to use with to open a file and read data from it.
Pickling
Write a Python program to create an Emp class with employee details as instance variables.
Write a Python program to pickle Emp class objects.
Write a Python program to unpickle Emp class objects.
Binary Files
Write a Python program to create a binary file and store records.
Write a Python program to randomly access a record from a binary file.
Write a Python program to search for a city name in a file and display the record number containing it.
Write a Python program to update/modify a record in a binary file.
Write a Python program to delete a specific record from a binary file.
Write a Python program to create a phone book containing names and phone numbers.
Write a Python program to use mmap and perform various operations on a binary file.
Write a Python program to compress the contents of files.
Directories
Write a Python program to display the contents of files available in a directory.
Write a Python program to display the current working directory.
Write a Python program to create a subdirectory and sub-subdirectory.
Write a Python program using makedirs() to create subdirectories.
Write a Python program to change to another directory.
Write a Python program to remove a subdirectory.
Write a Python program to remove a group of directories from a path.
Write a Python program to rename a directory.
Write a Python program to display all contents of the current directory.
Write a Python program to display Python program files available in the current directory.
Chapter 18 — Regular Expressions
Write a Python program using search() to find strings starting with m and having exactly 3 characters.
Write a Python program using findall() to find strings starting with m and having exactly 3 characters.
Write a Python program using match() to find strings starting with m and having exactly 3 characters.
Write a Python program using regular expressions to split a string wherever one or more non-alphanumeric characters occur.
Write a Python program using regular expressions to replace a string with a new string.
Write a Python program to retrieve all words starting with a.
Write a Python program to retrieve all words starting with a numeric digit.
Write a Python program to retrieve all words having exactly 5 characters.
Write a Python program using search() to retrieve a word having exactly 5 characters.
Write a Python program to retrieve all words satisfying a specified pattern.
Write a Python program to retrieve all words having 3, 4, or 5 characters.
Write a Python program to retrieve only single digits.
Write a Python program to retrieve the last word of a string.
Write a Python program to retrieve a person's phone number using regular expressions.
Write a Python program to extract only names and not numbers from a string.
Write a Python program to find all words starting with an or lak.
Write a Python program to retrieve dates of birth from a string.
Write a Python program to search whether a string starts with He.
Write a Python program to search for a word at the end of a string.
Write a Python program to search at the end of a string while ignoring case.
Write a Python program to retrieve marks and names from a string.
Write a Python program to retrieve timings ending in either am or pm.
Write a Python program to retrieve email IDs from a text.
Write a Python program to retrieve data from a file using regular expressions and write it into another file.
Write a Python program to retrieve information from an HTML file using regular expressions.
Chapter 19 — Data Structures in Python
Write a Python program to create a linked list and perform operations on it.
Write a Python program to create a Stack class that performs important stack operations.
Write a Python program to perform various operations on a stack using the Stack class.
Write a Python program to create a Queue class using list methods.
Write a Python program to perform operations on a queue.
Write a Python program to create and use deque.
Chapter 20 — Date and Time
Write a Python program to measure time in seconds since the epoch.
Write a Python program to get date and time from epoch time.
Write a Python program to convert epoch time into corresponding date and time.
Write a Python program to display the current date and time using ctime().
Write a Python program to display the local date and time.
Write a Python program to display today's date and time.
Write a Python program to create a datetime object by combining date and time objects.
Write a Python program to create a datetime object and modify its contents.
Write a Python program to convert a date into a required string format.
Write a Python program to find the day of the year and weekday name.
Write a Python program to format time using strftime().
Write a Python program to accept a date and display the day of the week.
Write a Python program to find the difference in days, weeks, and months between two dates.
Write a Python program to find the difference between two dates including time.
Write a Python program to find a future date and time from an existing date and time.
Write a Python program to display the next 10 dates continuously.
Write a Python program to accept the dates of birth of two persons and determine who is older.
Write a Python program to sort a group of dates in ascending order.
Write a Python program to generate random numbers in a range with a time delay between numbers.
Write a Python program to find the execution time of a program.
Write a Python program to accept a year and determine whether it is a leap year.
Write a Python program to display the calendar for a given month and year.
Write a Python program to display the calendar for all months of a given year.
Chapter 21 — Threads
Write a Python program to find the currently running thread.
Write a Python program to create a thread and use it to run a function.
Write a Python program to pass arguments to a function and execute it using a thread.
Write a Python program to create a thread by making a class a subclass of Thread.
Write a Python program to create a thread that accesses instance variables of a class.
Write a Python program to create a thread that acts on an object of a class that is not derived from Thread.
Write a Python program demonstrating single tasking using a thread that prepares tea.
Write a Python program that performs two tasks simultaneously using two threads.
Write a Python program where two threads act on the same method to allot a berth to a passenger.
Write a Python program to achieve thread synchronization using locks.
Write a Python program to demonstrate deadlock of threads due to locks.
Write a Python program with logic to avoid deadlocks.
Write a Python program where Producer and Consumer threads communicate using a Boolean variable.
Write a Python program demonstrating thread communication using notify() and wait() with a Condition object.
Write a Python program using a queue for thread communication.
Write a Python program to demonstrate the creation of a daemon thread.
Chapter 22 — Graphical User Interface
Write a Python program to create a root/top-level window.
Write a Python program to create a root window with options.
Write a Python program to display available font families.
Write a GUI program to create various shapes on a canvas.
Write a Python program to create arcs in different shapes.
Write a Python program to display images on a canvas.
Write a Python program to display drawings on a canvas.
Write a GUI program to display a frame in the root window.
Write a Python program to create a push button and bind it to an event-handler function.
Write a Python program to create a push button and bind it using the command option.
Write a Python program to create three push buttons and change the frame background according to the clicked button.
Write a Python program to display a label when a push button is clicked.
Write a Python program to display a message in a frame.
Write a Python program to create a Text widget with a vertical scrollbar, highlight the first line, and display an image.
Write a Python program to create a horizontal scrollbar and attach it to a Text widget.
Write a Python program to create three check buttons and determine which options are selected.
Write a Python program to create radio buttons and determine which button is selected.
Write a Python program to create Entry widgets for username and password and display the entered text.
Write a Python program to create two spin boxes and retrieve their values when a button is clicked.
Write a Python program to create a list box containing university names and display selected names in a text box.
Write a Python program to create a menu bar containing File and Edit menus.
Write a GUI program to create a menu and open/save files using file-dialog boxes.
Write a GUI program to display a table with rows and columns.
Chapter 23 — Networking in Python
Write a Python program to find the IP address of a website.
Write a Python program to retrieve different parts of a URL and display them.
Write a Python program to read the source code of a web page.
Write a Python program to download a web page from the Internet and save it on the computer.
Write a Python program to download an image from the Internet.
Write a Python program to create a TCP/IP server that sends messages to a client.
Write a Python program to create a TCP/IP client that receives messages from the server.
Write a Python program to create a UDP server that sends messages to a client.
Write a Python program to create a UDP client that receives messages from a server.
Write a Python program to create a file server that receives a filename from a client and sends the file contents.
Write a Python program to create a file client that sends a filename to the server and receives its contents.
Write a Python program to create a basic chat server.
Write a Python program to create a basic chat client.
Write a Python program to send an email to an email address.
Chapter 24 — Python Database Connectivity
Write a Python program to retrieve and display all rows from the employee table.
Write another Python program to retrieve and display all rows from the employee table.
Write a Python program to retrieve all rows from the employee table and display column values in tabular form.
Write a Python program to insert a row into a MySQL table.
Write a Python program to insert several rows into a table using keyboard input.
Write a Python program to delete a row from emptab by accepting the employee number.
Write a Python program to increase an employee's salary by accepting the employee number.
Write a Python program to create the emptab table in MySQL.
Write a Python GUI program to retrieve a row from a MySQL database table.
Write a Python program to connect to an Oracle database and retrieve rows from emptab.
Write a Python program to increase an employee's salary by accepting the employee number from the keyboard.
Write a Python program to execute a stored procedure and retrieve its results from an Oracle database.
📌 Total
Your cleaned list contains approximately 406 program questions across 19 chapters in the material you provided.
Most important chapters for practical/exam preparation
If your exam is mainly programming/practical, I would prioritize:
⭐ Chapter 5 — Input/Output
⭐ Chapter 6 — Control Statements
⭐ Chapter 7 — Arrays / NumPy
⭐ Chapter 8 — Strings
⭐ Chapter 9 — Functions
⭐ Chapter 10 — Lists/Tuples
⭐ Chapter 11 — Dictionaries
⭐ Chapter 13 — Classes & Objects
⭐ Chapter 14 — Inheritance/Polymorphism
⭐ Chapter 16 — Exceptions
⭐ Chapter 17 — Files
⭐ Chapter 18 — Regular Expressions
The later chapters—Threads, GUI, Networking, and Database Connectivity—are also important if they are included in your practical syllabus.
